Fixes the fatal PHP error that broke the plugin.
Error: 'PHP Fatal error: Array and string offset access syntax with curly braces is no longer supported'.